version: "3.9"
services:
  database:
    image: mongo:7-jammy
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=fullstack
    networks:
      - fullstack-network
    volumes:
      - fullstack-volume:/data/db

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=mongodb://admin:admin@database:27017/fullstack?authSource=admin
    depends_on:
      - database
    networks:
      - fullstack-network

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    networks:
      - fullstack-network
    environment:
      - VITE_API_URL=http://backend:3000

volumes:
  fullstack-volume:

networks:
  fullstack-network:
